git submodule add https://github.com/bobeobibo/phigaro
git submodule add https://github.com/linsalrob/PhiSpy
git submodule add https://github.com/refresh-bio/PHIST
git submodule add https://github.com/hzi-bifo/Phylogeography_Paper
git submodule add https://github.com/replikation/poreCov
git submodule add https://github.com/hoelzer/poseidon
git submodule add https://github.com/mg878/PoW_model
git submodule add https://github.com/zhenchengfang/PPR-Meta
git submodule add https://github.com/KleistLab/PrEP
git submodule add https://github.com/mariehoffmann/PriSeT
git submodule add https://github.com/jaumlrc/ProphET
git submodule add https://github.com/MGXlab/pvogs_function
git submodule add https://github.com/hzi-bifo/Quasimodo
git submodule add https://github.com/babaksaremi/RESEQ
git submodule add https://github.com/santa-dev/santa-sim
git submodule add https://github.com/virologyCharite/sars2seq
git submodule add https://github.com/gussow/seeker
git submodule add https://github.com/desiro/silentMutations
git submodule add https://github.com/soedinglab/spacepharer
git submodule add https://github.com/3BioCompBio/SpikeProSARS-CoV-2
git submodule add https://github.com/hzi-bifo/SDplots
git submodule add https://github.com/gruberlab/tabajara
git submodule add https://github.com/PierreBarrat/TreeKnit.jl
git submodule add https://github.com/nawrockie/vadr
git submodule add https://github.com/liuql2019/VFM
git submodule add https://github.com/AnantharamanLab/VIBRANT
git submodule add https://github.com/xunchen85/VIcaller
git submodule add https://github.com/flomock/vidhop
git submodule add https://github.com/EGTortuero/viga
git submodule add https://github.com/JCVenterInstitute/VIGOR4
git submodule add https://github.com/keylabivdc/VIP/
git submodule add https://github.com/ALFLAG/Viral_Variant_Visualiser
git submodule add https://github.com/ablab/viralComplete/
git submodule add https://github.com/dezordi/ViralFlow
git submodule add https://github.com/wclose/viralMetagenomicsPipeline
git submodule add https://github.com/nf-core/viralrecon
git submodule add https://github.com/ablab/viralVerify/
git submodule add https://github.com/NeuroCSUT/ViraMiner
git submodule add https://github.com/marieBvr/virAnnot
git submodule add https://github.com/jessieren/VirFinder
git submodule add https://github.com/jessieren/VirHostMatcher
git submodule add https://github.com/EBI-Metagenomics/emg-viral-pipeline
git submodule add https://github.com/thatzopoulos/virMine
git submodule add https://github.com/TingtZHENG/VirMiner
git submodule add https://github.com/alyosama/virnet
git submodule add https://github.com/simroux/VirSorter
git submodule add https://github.com/rega-cev/virulign
git submodule add https://github.com/rujinlong/virus_prediction
git submodule add https://github.com/NCBI-Hackathons/ViruSpy
git submodule add https://github.com/replikation/What_the_Phage
git submodule add https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe
git submodule add https://gitlab.com/dacs-hpi/deepac
git submodule add https://gitlab.com/dacs-hpi/deepac-live
git submodule add https://gitlab.com/rki_bioinformatics/ganon
git submodule add https://gitlab.com/rki_bioinformatics/LiveKraken
git submodule add https://gitlab.com/rki_bioinformatics/purple
git submodule add https://gitlab.com/mkuhring/TaxIt