git submodule add https://github.com/MathildeFogPerez/ancestree
git submodule add https://github.com/filipspl/AnnapuRNA
git submodule add https://github.com/hzi-bifo/PatchInference
git submodule add https://github.com/artic-network/fieldbioinformatics
git submodule add https://github.com/nextstrain/augur
git submodule add https://github.com/f-kretschmer/bertax
git submodule add https://github.com/CAMI-challenge/CAMISIM
git submodule add https://github.com/cesaregruber/CCHFV-PrimerChecker
git submodule add https://github.com/mtisza1/Cenote-Taker2
git submodule add https://github.com/KatyBrown/CIAlign
git submodule add https://github.com/usegalaxy-eu/ena-upload-cli
git submodule add https://github.com/cbg-ethz/cojac
git submodule add https://github.com/CovidStrategyCalculator/CovidStrategyCalculator
git submodule add https://github.com/TRON-Bioinformatics/covigator-ngs-pipeline
git submodule add https://github.com/acorg/dark-matter
git submodule add https://github.com/phiweger/darkq
git submodule add https://github.com/jessieren/DeepVirFinder
git submodule add https://github.com/spyros-lytras/dinuq
git submodule add https://github.com/DepledgeLab/DRUMMER
git submodule add https://github.com/MJmaolu/DVGfinder
git submodule add https://github.com/gruberlab/efinder
git submodule add https://github.com/Pbdas/epa-ng
git submodule add https://github.com/mcollatz/EpiDope
git submodule add https://github.com/hzi-bifo/epitope-prediction
git submodule add https://github.com/cesaregruber/ESCA
git submodule add https://github.com/vgupta1/EvaTargetedCovid19Testing
git submodule add https://github.com/hzi-bifo/FrechetTreeDistance
git submodule add https://github.com/KleistLab/GInPipe
git submodule add https://github.com/hzi-bifo/Haploflow
git submodule add https://github.com/shandley/hecatomb
git submodule add https://github.com/BDI-pathogens/HIV-phyloTSI
git submodule add https://github.com/gruberlab/hmmprospector
git submodule add https://github.com/plaffy/HoloVir
git submodule add https://github.com/sanger-pathogens/iva
git submodule add https://github.com/DennisSchmitz/Jovian
git submodule add https://github.com/dvs/hh-suite-notebooks/tree/LAMPA
git submodule add https://github.com/LaboratorioBioinformatica/MARVEL
git submodule add https://github.com/cbg-ethz/MC-CBN
git submodule add https://github.com/JCVenterInstitute/Meta-CATS
git submodule add https://github.com/MattiaPandolfoVR/MetaPhage
git submodule add https://github.com/vanessajurtz/MetaPhinder
git submodule add https://github.com/metaGmetapop/metapop
git submodule add https://github.com/RVanDamme/MUFFIN
git submodule add https://github.com/carolzhou/multiPhATE
git submodule add https://github.com/SushiLab/mVIRs
git submodule add https://github.com/Marleen1/OGRE
git submodule add https://github.com/bpickett/Pathway2Targets
git submodule add https://github.com/ku-cbd/PhageBoost
git submodule add https://github.com/jondeaton/PhaMers
git submodule add https://github.com/deprekate/PHANOTATE